const productos = [{
        id: 00,
        product: "PEN 1",
        img: "./img/Máquina.jpg",
        description: "Máquina de tatuaje para principiantes tipo pen.",
        price: 50,
        offer: true,
        category: "maquinas",
        subcategory: "pen",
    },
    {
        id: 01,
        product: "PEN 2",
        img: "./img/Maquina1.jpg",
        description: "Máquina para tatuar inalámbrica tipo pen con batería y regulador de voltaje.",
        price: 60,
        offer: false,
        category: "maquinas",
        subcategory: "pen",
    },
    {
        id: 02,
        product: "PEN 3",
        img: "./img/Maquina2.jpg",
        description: "Máquina profesional para tatuar inalámbrica tipo pen con batería.",
        price: 70,
        offer: false,
        category: "maquinas",
        subcategory: "pen",
    },
    {
        id: 03,
        product: "PEN 4",
        img: "./img/Maquina3.jpg",
        description: "Máquina para tatuar inalámbrica profesional tipo pen.",
        price: 70,
        offer: true,
        category: "maquinas",
        subcategory: "pen",
    },
    {
        id: 04,
        product: "PEN 5",
        img: "./img/Maquina4.jpg",
        description: "Máquina para tatuar inalámbrica profesional tipo pen con dos baterías de larga duración.",
        price: 100,
        offer: true,
        category: "maquinas",
        subcategory: "pen",
    },
    {
        id: 05,
        product: "BOBINAS 1",
        img: "./img/Maquina5.jpg",
        description: "Máquina para tatuar de bobinas con fuente de poder incluida.",
        price: 50,
        offer: false,
        category: "maquinas",
        subcategory: "bobinas",
    },
    {
        id: 06,
        product: "BOBINAS 2",
        img: "./img/Maquina6.jpg",
        description: "Máquina para tatuar de bobinas con fuente de poder incluida.",
        price: 45,
        offer: true,
        category: "maquinas",
        subcategory: "bobinas",
    },
    {
        id: 07,
        product: "ROTATIVA 1",
        img: "./img/Maquina7.jpg",
        description: "Máquina para tatuar rotativa con fuente de poder incluida.",
        price: 65,
        offer: false,
        category: "maquinas",
        subcategory: "rotativas",
    },
    {
        id: 08,
        product: "ROTATIVA 2",
        img: "./img/Maquina7.jpg",
        description: "Máquina para tatuar s con fuente de poder incluida.",
        price: 75,
        offer: true,
        category: "maquinas",
        subcategory: "rotativas",
    },
    {
        id: 09,
        product: "PIEL SINTÉTICA 1",
        img: "./img/PielSintética.jpg",
        description: "Pack de 10 pieles sintéticas para tatuar, tamaó de 15 x 20 cm.",
        price: 15,
        offer: false,
        category: "pieles",
        subcategory: "complementos",
    },
    {
        id: 10,
        product: "PIEL SINTÉTICA 2",
        img: "./img/PielSintética2.jpg",
        description: "Pack de 15 pieles sintéticas para tatuar, tamaó de 15 x 20 cm.",
        price: 20,
        offer: false,
        category: "pieles",
        subcategory: "complementos",
    },
    {
        id: 11,
        product: "TINTA NEGRA",
        img: "./img/Tinta1.jpg",
        description: "Tinta para tatuar color negro de 1Oz.",
        price: 4,
        offer: false,
        category: "tintas",
        subcategory: "complementos",
    },
    {
        id: 12,
        product: "TINTA NEGRA 2",
        img: "./img/Tinta2.jpg",
        description: "Tinta para tatuar color negro de 2Oz.",
        price: 9,
        offer: false,
        category: "tintas",
        subcategory: "complementos",
    },
    {
        id: 13,
        product: "TINTA ROJA",
        img: "./img/Tinta3.jpg",
        description: "Tinta para tatuar color rojo de 1Oz.",
        price: 5,
        offer: true,
        category: "tintas",
        subcategory: "complementos",
    },
    {
        id: 14,
        product: "TINTA BLANCA",
        img: "./img/Tinta4.jpg",
        description: "Tinta para tatuar color blanco de 1Oz.",
        price: 6,
        offer: false,
        category: "tintas",
        subcategory: "complementos",
    },
    {
        id: 15,
        product: "PACK TINTAS",
        img: "./img/Tinta5.jpg",
        description: "Pack de 3 tintas de 1 Oz,colores a elegir",
        price: 15,
        offer: true,
        category: "tintas",
        subcategory: "complementos",
    },
    {
        id: 16,
        product: "KIT TATUAJE PARA PRINCIPIANTES 1",
        img: "./img/Maquina4.jpg",
        description: "Máquina de Bobinas / Fuente de poder / Tinta para practicar / 2 pieles sintéticas / 20 agujas / 20 cartuchos.",
        price: 90,
        offer: true,
        category: "maquinas",
        subcategory: "kits",
    },
    {
        id: 17,
        product: "KIT TATUAJE PARA PRINCIPIANTES 2",
        img: "./img/Maquina4.jpg",
        description: "Máquina rotativa tipo pen / Fuente de poder / Tinta para practicar / 2 pieles sintéticas / 20 agujas / 20 cartuchos.",
        price: 130,
        offer: false,
        category: "maquinas",
        subcategory: "kits",
    },
];